# Generated by Django 2.2 on 2020-11-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_dash_app', '0002_quotepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotepost',
            name='likes',
            field=models.ManyToManyField(related_name='like_post', to='quote_dash_app.User'),
        ),
    ]
